"""VASPen — Main entry point.

Launches the QApplication, main window, and event loop.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtCore import QSize
from PySide6.QtWidgets import QApplication
from PySide6.QtGui import QIcon

from vaspen.ui.main_window import MainWindow
from vaspen.utils.config import AppConfig
from vaspen.utils.logger import logger, setup_logger

#: Windows taskbar identity — deliberately NOT versioned, so taskbar
#: grouping stays stable across upgrades. Must be set BEFORE the first
#: window is created (Explorer binds the taskbar button to the host
#: process — python.exe in dev mode — when the first window is shown;
#: setting it afterwards was the "icon sometimes displays, sometimes
#: doesn't" bug).
WINDOWS_APP_USER_MODEL_ID = "VASPen"


def _icons_dir() -> Path:
    """Icons directory, valid in dev and in the frozen app.

    PyInstaller onedir flattens the entry script to ``_internal/
    main.py`` while the bundled data keeps the package layout
    (``_internal/vaspen/resources``) — so a ``__file__``-relative
    path is wrong when frozen; use the extraction dir instead.
    """
    if getattr(sys, "_MEIPASS", None):
        return Path(sys._MEIPASS) / "vaspen" / "resources" / "icons"
    return Path(__file__).parent / "resources" / "icons"


def _load_app_icon(icons_dir: Path) -> QIcon:
    """Build a multi-size icon so Windows picks the crispiest match.

    Uses the per-size square letterboxed PNGs (16-256) generated by
    scripts/make_icon.py from the full source artwork; falls back to
    the square app.png. Logs a warning instead of silently returning a
    null icon.
    """
    icon = QIcon()
    for size in (16, 24, 32, 48, 64, 128, 256):
        path = icons_dir / f"app_{size}.png"
        if path.exists():
            icon.addFile(str(path), QSize(size, size))
    if icon.isNull() and (icons_dir / "app.png").exists():
        icon = QIcon(str(icons_dir / "app.png"))
    if icon.isNull():
        logger.warning(
            "No app icon found in %s — the window will use the "
            "default icon", icons_dir)
    return icon


def _set_windows_app_id() -> None:
    """Bind the taskbar identity before any window is created."""
    if sys.platform != "win32":
        return
    try:
        import ctypes
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
            WINDOWS_APP_USER_MODEL_ID)
    except Exception as exc:
        logger.warning(
            "SetCurrentProcessExplicitAppUserModelID failed: %s", exc)


def main() -> int:
    """Application entry point.

    Returns:
        0 on normal exit, non-zero on error.
    """
    # --- Application ---
    app = QApplication(sys.argv)
    app.setApplicationName("VASPen")
    app.setApplicationVersion("0.2.0")
    app.setOrganizationName("VASPen")
    app.setOrganizationDomain("vaspen.dev")

    # --- Logger ---
    logger = setup_logger()

    # --- Windows taskbar identity (dev mode otherwise shows python.exe) ---
    # MUST run before the main window is created: Explorer reads the
    # AppUserModelID when the process's first window is shown.
    _set_windows_app_id()

    # --- Icon (set before show; Qt propagates it to the HWND itself) ---
    icons_dir = _icons_dir()
    icon = _load_app_icon(icons_dir)
    app.setWindowIcon(icon)

    # --- Main Window (loads translations itself; switchable live) ---
    config = AppConfig()
    lang = config.language
    window = MainWindow()
    window.setWindowIcon(icon)
    window.show()

    # Open a file passed on the command line (e.g. double-click file association)
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
        if Path(filepath).exists():
            window._open_file(filepath)
            logger.info("Opened CLI file: %s", filepath)
        else:
            logger.warning("CLI file not found: %s", filepath)

    logger.info("VASPen started (lang=%s)", lang)

    # --- Event Loop ---
    exit_code = app.exec()

    # --- Cleanup ---
    logger.info("VASPen exiting (code=%d)", exit_code)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
